### ISSUE TITLE
QuickEdit page errors

### ISSUE THREAD

**Issue by paulnagle** [bmlt-enabled/bmlt-workflow#101] opened 2022-10-04 09:01 UTC
When opening the QuickEdit page from a meeting change submission in the list of submissions, the Postcode format is restricted to a numerical format. It should allow free formatting, like the original submission does.

Also, the QuickEdit page does not show the correct SubProvince. In the NA Ireland setup the "SubProvince" choices are pre-filled from the configuration file on the BMLT. i.e.
`    $meeting_counties_and_sub_provinces = array('Antrim','Carlow','Cavan','Clare','Cork','Derry','Donegal','Down','Dublin','Galway','Kerry','Kildare','Kilkenny','Laois','Leitrim','Limerick','Longford','Louth','Mayo','Meath','Monaghan','Offaly','Roscommon','Sligo','Tipperary','Tryone','Tyrone','Waterford','Westmeath','Wexford','Wicklow');`

On the form where the original submission is created, the sub province get populated correctly, but on the QuickSubmission page is it always set to the first element of the array, i.e. 'Antrim' in this case.

**Comment by nigel-bmlt** [comment] 2022-10-04 11:26
Could you attach a screenshot of this? I'm not able to reproduce it on my end, I'm seeing it populate both quickedit and form page the same way.

> Also, the QuickEdit page does not show the correct SubProvince. In the NA Ireland setup the "SubProvince" choices are pre-filled from the configuration file on the BMLT. i.e. ` $meeting_counties_and_sub_provinces = array('Antrim','Carlow','Cavan','Clare','Cork','Derry','Donegal','Down','Dublin','Galway','Kerry','Kildare','Kilkenny','Laois','Leitrim','Limerick','Longford','Louth','Mayo','Meath','Monaghan','Offaly','Roscommon','Sligo','Tipperary','Tryone','Tyrone','Waterford','Westmeath','Wexford','Wicklow');`
> 
> On the form where the original submission is created, the sub province get populated correctly, but on the QuickSubmission page is it always set to the first element of the array, i.e. 'Antrim' in this case.

**Comment by nigel-bmlt** [comment] 2022-10-04 11:27
Postcode in quickedit numerical only fixed in 1.0.8

**Comment by paulnagle** [comment] 2022-10-04 12:28
Here's a 3 minute videe of what I see...

https://user-images.githubusercontent.com/3714999/193819002-357c2e90-389c-47ee-877e-96102f7820dc.mp4

**Comment by paulnagle** [comment] 2022-10-04 12:29
Heres a 3 minute video of what I see with the subprovince changing....


https://user-images.githubusercontent.com/3714999/193819300-9e5e664f-33cf-4c84-8eee-6c9131fa62b4.mp4

**Comment by nigel-bmlt** [comment] 2022-10-04 21:04
Thanks. I know the issue now and will fix shortly

**Comment by nigel-bmlt** [comment] 2022-10-05 05:57
fixed in 1.0.8

**Closed by nigel-bmlt** 2022-10-05 05:57 UTC
