### ISSUE TITLE
Enhancement

### ISSUE THREAD

**Issue by Klodd65** [bmlt-enabled/bmlt-workflow#174] opened 2023-03-29 00:27 UTC
#enhancement

Is it possible to make the choice of those format (wheelchair accessibility or not and open or closed meeting) mandatory?

**Comment by nigel-bmlt** [comment] 2023-03-29 08:51
duplicate of https://github.com/bmlt-enabled/bmlt-workflow/issues/32 - will bring this up in the root server discussion for thoughts

**Closed** 2023-09-15 16:00 UTC
